/*
 * Copyright 2026 Bada contributors.
 *
 * Licensed under the Apache License, Version 2.0.
 */
package dev.bluehouse.bada.protocol.test

/**
 * Deterministic Known-Answer Test (KAT) vectors for the Quick Share
 * QR-code path.
 *
 * These vectors are computed off-line from the documented HKDF-SHA256
 * derivation:
 *
 * ```
 * advertisingToken    = HKDF-SHA256(ikm=keyData, salt="", info="advertisingContext", L=16)
 * nameEncryptionKey   = HKDF-SHA256(ikm=keyData, salt="", info="encryptionKey",      L=16)
 * ```
 *
 * They live in `:core-protocol-test` so the **same** KAT can be reused from
 * both the JVM unit test in `:core-protocol` and any future Android
 * instrumentation tests that re-validate the protocol stack on real
 * hardware. Reusing the fixtures means we never accidentally compute
 * "expected" outputs from the implementation under test in an Android
 * test — the answers are pinned in source.
 *
 * The expected outputs were generated by running the reference HKDF-SHA256
 * (this codebase's [dev.bluehouse.bada.protocol.crypto.Hkdf], which is
 * itself locked down by the RFC 5869 Appendix A vectors) over the documented
 * keyData layouts and recorded as hex strings here.
 */
public object QrCodeVectors {
    /**
     * One QR-code key-derivation KAT vector. Plain class, not a `data class`,
     * for the same `ByteArray` equality reason called out in [HkdfVectors].
     */
    public class Vector(
        public val name: String,
        public val keyData: ByteArray,
        public val expectedAdvertisingToken: ByteArray,
        public val expectedNameEncryptionKey: ByteArray,
    ) {
        override fun toString(): String = name
    }

    /**
     * Vector 1 — version byte `0x02`, X coordinate = `0x01..0x20` (every
     * value in the lowest 32 byte values, in order). The fully-zero leading
     * two bytes of the version prefix are exercised by the [keyData] layout
     * itself.
     */
    public val testCase1: Vector =
        Vector(
            name = "QR keyData v=0x02, X=01..20",
            keyData =
                hex(
                    "000002" +
                        "0102030405060708090a0b0c0d0e0f10" +
                        "1112131415161718191a1b1c1d1e1f20",
                ),
            expectedAdvertisingToken = hex("0437d95175045e8ce8dc777e93b6c358"),
            expectedNameEncryptionKey = hex("39cfade1d68ccfdfe2b882e84d4e3860"),
        )

    /**
     * Vector 2 — version byte `0x03`, X coordinate = all `0xAA`. Pins down
     * the alternative version-byte path and a saturated X.
     */
    public val testCase2: Vector =
        Vector(
            name = "QR keyData v=0x03, X=all 0xAA",
            keyData =
                hex(
                    "000003" +
                        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" +
                        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                ),
            expectedAdvertisingToken = hex("5ba5b5072df4b4e225bfc97042972568"),
            expectedNameEncryptionKey = hex("d629886879e71bbf79024b9b7180fcba"),
        )

    /**
     * Vector 3 — version byte `0x02`, X coordinate = all zero. Pins down
     * the degenerate "X = 0" path and confirms that the HKDF derivation
     * still produces the documented output when the IKM is mostly zeros.
     */
    public val testCase3: Vector =
        Vector(
            name = "QR keyData v=0x02, X=all zero",
            keyData =
                hex(
                    "000002" +
                        "00000000000000000000000000000000" +
                        "00000000000000000000000000000000",
                ),
            expectedAdvertisingToken = hex("f02fb02da9ef3b6b4696ce326d4591d4"),
            expectedNameEncryptionKey = hex("5d365c2e7651efdcd7a09f82ba8c13f0"),
        )

    /** All Quick Share QR-code KAT vectors in declaration order. */
    public val all: List<Vector> = listOf(testCase1, testCase2, testCase3)

    private fun hex(value: String): ByteArray {
        require(value.length % 2 == 0) { "Hex string must have even length: ${value.length}" }
        val out = ByteArray(value.length / 2)
        for (i in out.indices) {
            val hi = decodeNibble(value[i * 2])
            val lo = decodeNibble(value[i * 2 + 1])
            out[i] = ((hi shl 4) or lo).toByte()
        }
        return out
    }

    private fun decodeNibble(c: Char): Int =
        when (c) {
            in '0'..'9' -> c - '0'
            in 'a'..'f' -> c - 'a' + 10
            else -> throw IllegalArgumentException("Invalid hex character: '$c'")
        }
}
